import Head from 'next/head'
// import '../styles/globals.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Horizon Free</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/HORIZON FREE.png" />
      </Head>
      <div>
        <h1>Hello world</h1>
      </div>
    </>
  )
}
